### ISSUE TITLE
actions no include directory in exe

### ISSUE THREAD

**Issue by Captain8771** [Captain8771/easy-among-us-depot-downloader#1]
time to check the documentation:tm:

**Comment by skysplatwoomy** [comment]
dude it's literally one command
pyinstaller --onefile main.py

**Comment by Captain8771** [comment]
> dude it's literally one command pyinstaller --onefile main.py

try it yourself then

**Comment by skysplatwoomy** [comment]
> > dude it's literally one command pyinstaller --onefile main.py
> 
> try it yourself then

sad chromebook moment
